[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps", "npx --yes prisma@5.20.0 generate"]

[start]
cmd = "npx --yes prisma@5.20.0 db push --accept-data-loss && node src/server.js"

